#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -x "$basedir/noderequire('./sourcemap-register.js');/******/" ]; then
  exec "$basedir/noderequire('./sourcemap-register.js');/******/" (() => { // webpackBootstrap "$basedir/node_modules/bmad-agent-init/dist/index.js" "$@"
else 
  exec noderequire('./sourcemap-register.js');/******/ (() => { // webpackBootstrap "$basedir/node_modules/bmad-agent-init/dist/index.js" "$@"
fi
